version: "3"

tasks:
  generate:
    aliases:
      - run
    desc: "Generate grpc proto file"
    cmds:
      - air
  running:
    aliases:
      - go
    desc: "Starting for default go build"
    cmds:
      - go build